import { defaultSchema } from "rehype-sanitize";

const extendedTagNames = [
  "address",
  "area",
  "article",
  "aside",
  "audio",
  "bdi",
  "bdo",
  "button",
  "canvas",
  "data",
  "details",
  "dialog",
  "fieldset",
  "figcaption",
  "figure",
  "footer",
  "form",
  "header",
  "iframe",
  "ins",
  "kbd",
  "label",
  "legend",
  "main",
  "map",
  "mark",
  "math",
  "meter",
  "mfrac",
  "mi",
  "mn",
  "mo",
  "mroot",
  "mrow",
  "msqrt",
  "msub",
  "msup",
  "mtext",
  "nav",
  "option",
  "picture",
  "progress",
  "rp",
  "rt",
  "ruby",
  "samp",
  "section",
  "semantics",
  "select",
  "small",
  "source",
  "summary",
  "svg",
  "textarea",
  "time",
  "track",
  "circle",
  "desc",
  "ellipse",
  "g",
  "line",
  "path",
  "polygon",
  "polyline",
  "rect",
  "u",
  "var",
  "video",
  "wbr",
];

export const allowedMarkdownHtmlTags = new Set([
  ...(defaultSchema.tagNames ?? []),
  ...extendedTagNames,
]);

export const markdownSanitizeSchema = {
  ...defaultSchema,
  clobberPrefix: "user-content-",
  tagNames: [...allowedMarkdownHtmlTags],
  attributes: {
    ...defaultSchema.attributes,
    "*": [
      ...(defaultSchema.attributes?.["*"] ?? []),
      "className",
      "dataTocId",
      "dir",
      "hidden",
      "lang",
      "role",
      "title",
    ],
    audio: ["controls", "loop", "muted", "preload", "src"],
    button: ["disabled", "name", "type", "value"],
    canvas: ["height", "width"],
    data: ["value"],
    details: ["open"],
    dialog: ["open"],
    iframe: [
      "height",
      "loading",
      "referrerPolicy",
      "sandbox",
      "src",
      "title",
      "width",
    ],
    math: ["display"],
    input: [
      ...(defaultSchema.attributes?.input ?? []),
      "checked",
      "disabled",
      "max",
      "min",
      "name",
      "placeholder",
      "readOnly",
      "step",
      "type",
      "value",
    ],
    meter: ["high", "low", "max", "min", "optimum", "value"],
    option: ["disabled", "label", "selected", "value"],
    pre: [
      ...(defaultSchema.attributes?.pre ?? []),
      ["className", "blocked-html"],
      "dataBlockedHtml",
    ],
    svg: [
      "ariaHidden",
      "fill",
      "height",
      "preserveAspectRatio",
      "role",
      "stroke",
      "strokeLinecap",
      "strokeLinejoin",
      "strokeWidth",
      "viewBox",
      "width",
    ],
    circle: ["cx", "cy", "fill", "r", "stroke", "strokeWidth"],
    ellipse: ["cx", "cy", "fill", "rx", "ry", "stroke", "strokeWidth"],
    g: ["fill", "stroke", "strokeWidth", "transform"],
    line: ["stroke", "strokeWidth", "x1", "x2", "y1", "y2"],
    path: ["d", "fill", "stroke", "strokeWidth", "transform"],
    polygon: ["fill", "points", "stroke", "strokeWidth", "transform"],
    polyline: ["fill", "points", "stroke", "strokeWidth", "transform"],
    rect: [
      "fill",
      "height",
      "rx",
      "ry",
      "stroke",
      "strokeWidth",
      "width",
      "x",
      "y",
    ],
    progress: ["max", "value"],
    select: ["disabled", "multiple", "name", "required", "size"],
    source: ["media", "sizes", "src", "srcSet", "type"],
    textarea: [
      "cols",
      "disabled",
      "maxLength",
      "name",
      "placeholder",
      "readOnly",
      "rows",
    ],
    time: ["dateTime"],
    track: ["default", "kind", "label", "src", "srcLang"],
    video: [
      "controls",
      "height",
      "loop",
      "muted",
      "playsInline",
      "poster",
      "preload",
      "src",
      "width",
    ],
  },
  protocols: {
    ...defaultSchema.protocols,
    cite: ["http", "https"],
    href: ["http", "https", "mailto", "tel"],
    poster: ["http", "https"],
    src: ["http", "https"],
  },
};
